spring.application.name=atalaya
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=8080

logging.pattern.dateformat=hh:mm
spring.main.banner-mode=off
spring.thymeleaf.cache=false

# Conexion a la BD MySQL en Aiven
spring.datasource.url=${DB_URL}

# Usuario y contrasena
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Propiedades para enviar correos mediante la API HTTPS de MailerSend
mailersend.api-token=${MAILERSEND_API_TOKEN:}
mailersend.from=${MAIL_FROM:}

# Informacion para Firebase Storage
firebase.bucket.name=atalaya-65141.firebasestorage.app
firebase.storage.path=atalaya
firebase.json.path=firebase
firebase.json.file=atalaya-65141-firebase-adminsdk-fbsvc-5c3535b580.json
